package battleship_gui;

import java.awt.Color;


/**
 *
 * @author John Decker
 */
public class TextInputs extends javax.swing.JFrame {
    
    RegExCheck validate = new RegExCheck();
    Color correct = new Color(102,255,102);
    Color wrong = new Color(255,102,102);
    JFrame_Battleship game;

    /**
     * Creates new form TextInputs
     */
    public TextInputs() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        setResizable(false);
        setTitle("Sign Up or Login");
        
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSignUpLogin = new javax.swing.JPanel();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        emailErrorLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        signInButton = new javax.swing.JButton();
        usernameField2 = new javax.swing.JTextField();
        passwordErrorLabel = new javax.swing.JLabel();
        passwordField2 = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        usernameErrorLabel = new javax.swing.JLabel();
        checkButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        signUpLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        smallbackgroundImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSignUpLogin.setMinimumSize(new java.awt.Dimension(640, 461));
        jSignUpLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstNameField.setText("First name");
        firstNameField.setPreferredSize(new java.awt.Dimension(200, 30));
        firstNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstNameFieldFocusLost(evt);
            }
        });
        jSignUpLogin.add(firstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 115, -1, -1));

        lastNameField.setText("Last name");
        lastNameField.setPreferredSize(new java.awt.Dimension(200, 30));
        lastNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastNameFieldFocusLost(evt);
            }
        });
        jSignUpLogin.add(lastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 163, -1, -1));

        emailField.setText("Email address");
        emailField.setPreferredSize(new java.awt.Dimension(200, 30));
        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFieldFocusLost(evt);
            }
        });
        jSignUpLogin.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        emailErrorLabel.setVisible(false);
        emailErrorLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        emailErrorLabel.setForeground(new java.awt.Color(255, 102, 102));
        emailErrorLabel.setText("Please enter valid email address\n");
        jSignUpLogin.add(emailErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        passwordField.setText("Password");
        passwordField.setPreferredSize(new java.awt.Dimension(200, 30));
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldFocusLost(evt);
            }
        });
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        jSignUpLogin.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        signInButton.setBackground(new java.awt.Color(102, 102, 102));
        signInButton.setForeground(new java.awt.Color(204, 204, 204));
        signInButton.setText("Sign in");
        signInButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.lightGray, java.awt.Color.white));
        signInButton.setPreferredSize(new java.awt.Dimension(70, 40));
        signInButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signInButtonMouseClicked(evt);
            }
        });
        jSignUpLogin.add(signInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 90, -1));

        usernameField2.setText("Username");
        usernameField2.setPreferredSize(new java.awt.Dimension(200, 30));
        usernameField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameField2FocusLost(evt);
            }
        });
        jSignUpLogin.add(usernameField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));

        passwordErrorLabel.setVisible(false);
        passwordErrorLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        passwordErrorLabel.setForeground(new java.awt.Color(255, 102, 102));
        passwordErrorLabel.setText("Must contain 1 uppercase, 1 lowercase, 1 numeric, 8 - 15 chars.");
        jSignUpLogin.add(passwordErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        passwordField2.setText("Password");
        passwordField2.setPreferredSize(new java.awt.Dimension(200, 30));
        passwordField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordField2FocusLost(evt);
            }
        });
        jSignUpLogin.add(passwordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));

        usernameField.setText("Username");
        usernameField.setPreferredSize(new java.awt.Dimension(200, 30));
        usernameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFieldFocusLost(evt);
            }
        });
        jSignUpLogin.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        usernameErrorLabel.setVisible(false);
        usernameErrorLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        usernameErrorLabel.setForeground(new java.awt.Color(255, 102, 102));
        usernameErrorLabel.setText("Must contain 1 lowercase, 4 - 10 chars");
        jSignUpLogin.add(usernameErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        checkButton.setBackground(new java.awt.Color(102, 102, 102));
        checkButton.setForeground(new java.awt.Color(204, 204, 204));
        checkButton.setText("check");
        checkButton.setToolTipText("Check username availablitiy");
        checkButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.lightGray, java.awt.Color.white));
        checkButton.setPreferredSize(new java.awt.Dimension(80, 40));
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });
        jSignUpLogin.add(checkButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 70, 30));

        registerButton.setBackground(new java.awt.Color(102, 102, 102));
        registerButton.setForeground(new java.awt.Color(204, 204, 204));
        registerButton.setText("Register");
        registerButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white));
        registerButton.setPreferredSize(new java.awt.Dimension(80, 40));
        registerButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                registerButtonMouseMoved(evt);
            }
        });
        registerButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                registerButtonFocusLost(evt);
            }
        });
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
        });
        jSignUpLogin.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 100, -1));

        signUpLabel.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
        signUpLabel.setForeground(new java.awt.Color(204, 204, 204));
        signUpLabel.setText("Sign Up");
        jSignUpLogin.add(signUpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 170, 50));

        loginLabel.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(204, 204, 204));
        loginLabel.setText("Login");
        jSignUpLogin.add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        smallbackgroundImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/battleship_gui/BSBackground_small.jpg"))); // NOI18N
        smallbackgroundImageLabel.setToolTipText("Check username availablitiy");
        jSignUpLogin.add(smallbackgroundImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSignUpLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSignUpLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameFieldFocusLost
        // TODO add your handling code here:
        
        if(validate.checkFirstName(firstNameField.getText())){
            firstNameField.setBackground(correct);
        }
        else
        firstNameField.setBackground(wrong);
    }//GEN-LAST:event_firstNameFieldFocusLost

    private void lastNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFieldFocusLost
        // TODO add your handling code here:
        if(validate.checkLastName(lastNameField.getText())){
            lastNameField.setBackground(correct);
        }
        else
        lastNameField.setBackground(wrong);
    }//GEN-LAST:event_lastNameFieldFocusLost

    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost
        // TODO add your handling code here:
        if(validate.checkEmail(emailField.getText())){
            emailErrorLabel.setVisible(false);
            emailField.setBackground(correct);
        }
        else {
            emailErrorLabel.setVisible(true);
            emailField.setBackground(wrong);
        }
    }//GEN-LAST:event_emailFieldFocusLost

    private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
        // TODO add your handling code here:
        if(validate.checkPasswd(passwordField.getText())){
            passwordErrorLabel.setVisible(false);
            passwordField.setBackground(correct);
        }
        else {
            passwordErrorLabel.setVisible(true);
            passwordField.setBackground(wrong);
        }
    }//GEN-LAST:event_passwordFieldFocusLost

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void usernameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFieldFocusLost
        // TODO add your handling code here:
        if(validate.checkUsrnm(usernameField.getText())){
            usernameErrorLabel.setVisible(false);
            usernameField.setBackground(correct);
        }
        else {
            usernameErrorLabel.setVisible(true);
            usernameField.setBackground(wrong);
        }
    }//GEN-LAST:event_usernameFieldFocusLost

    private void usernameField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameField2FocusLost
        // TODO add your handling code here:
        if(usernameField2.getText().length()!=0){
            usernameField2.setBackground(correct);
            
        }
        else {
            usernameField2.setBackground(wrong);
        }
    }//GEN-LAST:event_usernameField2FocusLost

    private void passwordField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordField2FocusLost
        // TODO add your handling code here:
        if(passwordField2.getText().length()!=0){
            passwordField2.setBackground(correct);
        }
        else
        passwordField2.setBackground(wrong);
    }//GEN-LAST:event_passwordField2FocusLost

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkButtonActionPerformed

    private void signInButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInButtonMouseClicked
        // TODO add your handling code here:
        
        game.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_signInButtonMouseClicked

    private void registerButtonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerButtonFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_registerButtonFocusLost

    private void registerButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseMoved
        // TODO add your handling code here:
        
        //if all the textfields are validated, user can click register button
        if(validate.checkFirstName(firstNameField.getText()) && 
                validate.checkLastName(lastNameField.getText()) &&
                validate.checkUsrnm(usernameField.getText()) &&
                validate.checkEmail(emailField.getText()) &&
                validate.checkPasswd(passwordField.getText())) {
            registerButton.setEnabled(true);
        } else {
            registerButton.setEnabled(false);
        }
    }//GEN-LAST:event_registerButtonMouseMoved

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked
        // TODO add your handling code here:
        if(registerButton.isEnabled()){
            //makes a new game
            game.reset();
            game.setVisible(true);
            //sets players name as username
            game.setPlayersName(usernameField.getText());
            //closes the jframe
            dispose();
        }
    }//GEN-LAST:event_registerButtonMouseClicked
    
    public void setBattleshipFrame(JFrame_Battleship bs){
        game = bs;
    }
    

    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkButton;
    private javax.swing.JLabel emailErrorLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JPanel jSignUpLogin;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel passwordErrorLabel;
    private javax.swing.JTextField passwordField;
    private javax.swing.JTextField passwordField2;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton signInButton;
    private javax.swing.JLabel signUpLabel;
    private javax.swing.JLabel smallbackgroundImageLabel;
    private javax.swing.JLabel usernameErrorLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JTextField usernameField2;
    // End of variables declaration//GEN-END:variables
}
