/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package battleship;

/**
 *
 * @author rcc
 */
public class BattleshipFrame extends javax.swing.JFrame {

    /**
     * Creates new form BattleshipFrame
     */
    public BattleshipFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startPane = new javax.swing.JLayeredPane();
        battleshipLogo = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        rulesButton = new javax.swing.JButton();
        highscoresButton = new javax.swing.JButton();
        nameEntry = new javax.swing.JTextField();
        rulesPane = new javax.swing.JLayeredPane();
        rulesLabel = new javax.swing.JLabel();
        rulesText = new javax.swing.JLabel();
        rulesClose = new javax.swing.JButton();
        gameplayPane = new javax.swing.JLayeredPane();
        gamePlayerBoard = new javax.swing.JLayeredPane();
        gameAIBoard = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        startPane.setMaximumSize(new java.awt.Dimension(800, 600));

        battleshipLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/battleship/battleship-movie-logo.png"))); // NOI18N

        startButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        startButton.setText("Start");
        startButton.setMaximumSize(new java.awt.Dimension(130, 40));
        startButton.setMinimumSize(new java.awt.Dimension(130, 40));
        startButton.setPreferredSize(new java.awt.Dimension(130, 40));
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        rulesButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rulesButton.setText("Rules");
        rulesButton.setPreferredSize(new java.awt.Dimension(130, 40));

        highscoresButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        highscoresButton.setText("High Scores");
        highscoresButton.setPreferredSize(new java.awt.Dimension(130, 40));

        nameEntry.setText("Enter your name");
        nameEntry.setPreferredSize(new java.awt.Dimension(60, 20));
        nameEntry.setRequestFocusEnabled(false);

        javax.swing.GroupLayout startPaneLayout = new javax.swing.GroupLayout(startPane);
        startPane.setLayout(startPaneLayout);
        startPaneLayout.setHorizontalGroup(
            startPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPaneLayout.createSequentialGroup()
                .addGroup(startPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startPaneLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(battleshipLogo))
                    .addGroup(startPaneLayout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addGroup(startPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rulesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(highscoresButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(startPaneLayout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(nameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        startPaneLayout.setVerticalGroup(
            startPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPaneLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(battleshipLogo)
                .addGap(48, 48, 48)
                .addComponent(nameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(rulesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(highscoresButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        startPane.setLayer(battleshipLogo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        startPane.setLayer(startButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        startPane.setLayer(rulesButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        startPane.setLayer(highscoresButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        startPane.setLayer(nameEntry, javax.swing.JLayeredPane.DEFAULT_LAYER);

        rulesPane.setMaximumSize(new java.awt.Dimension(800, 600));
        rulesPane.setMinimumSize(new java.awt.Dimension(800, 600));

        rulesLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        rulesLabel.setText("Rules for Battleship");

        rulesText.setText("User chooses a spot on the grid to strike.  If the user guesses right, the board will show a marker for a \"hit\".  If the user guesses wrong it will display a \"miss\".");

        rulesClose.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rulesClose.setLabel("Close");
        rulesClose.setMaximumSize(new java.awt.Dimension(130, 40));
        rulesClose.setMinimumSize(new java.awt.Dimension(130, 40));
        rulesClose.setPreferredSize(new java.awt.Dimension(130, 40));

        javax.swing.GroupLayout rulesPaneLayout = new javax.swing.GroupLayout(rulesPane);
        rulesPane.setLayout(rulesPaneLayout);
        rulesPaneLayout.setHorizontalGroup(
            rulesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rulesPaneLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(rulesText)
                .addGap(0, 27, Short.MAX_VALUE))
            .addGroup(rulesPaneLayout.createSequentialGroup()
                .addGroup(rulesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rulesPaneLayout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(rulesClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rulesPaneLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(rulesLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rulesPaneLayout.setVerticalGroup(
            rulesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rulesPaneLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(rulesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(rulesText, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(rulesClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        rulesPane.setLayer(rulesLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        rulesPane.setLayer(rulesText, javax.swing.JLayeredPane.DEFAULT_LAYER);

        rulesText.getAccessibleContext().setAccessibleName("User chooses a spot on the grid to strike.  If the user guesses right, the board will show a marker for a \"hit\".  If the user guesses wrong it will display a \"miss.\"");
        rulesText.getAccessibleContext().setAccessibleDescription("");
        rulesPane.setLayer(rulesClose, javax.swing.JLayeredPane.DEFAULT_LAYER);

        gamePlayerBoard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gamePlayerBoard.setMaximumSize(new java.awt.Dimension(360, 360));
        gamePlayerBoard.setMinimumSize(new java.awt.Dimension(360, 360));
        gamePlayerBoard.setPreferredSize(new java.awt.Dimension(360, 360));

        javax.swing.GroupLayout gamePlayerBoardLayout = new javax.swing.GroupLayout(gamePlayerBoard);
        gamePlayerBoard.setLayout(gamePlayerBoardLayout);
        gamePlayerBoardLayout.setHorizontalGroup(
            gamePlayerBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );
        gamePlayerBoardLayout.setVerticalGroup(
            gamePlayerBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );

        gameAIBoard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gameAIBoard.setMaximumSize(new java.awt.Dimension(360, 360));
        gameAIBoard.setMinimumSize(new java.awt.Dimension(360, 360));
        gameAIBoard.setPreferredSize(new java.awt.Dimension(360, 360));

        javax.swing.GroupLayout gameAIBoardLayout = new javax.swing.GroupLayout(gameAIBoard);
        gameAIBoard.setLayout(gameAIBoardLayout);
        gameAIBoardLayout.setHorizontalGroup(
            gameAIBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );
        gameAIBoardLayout.setVerticalGroup(
            gameAIBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout gameplayPaneLayout = new javax.swing.GroupLayout(gameplayPane);
        gameplayPane.setLayout(gameplayPaneLayout);
        gameplayPaneLayout.setHorizontalGroup(
            gameplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameplayPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gamePlayerBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gameAIBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        gameplayPaneLayout.setVerticalGroup(
            gameplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameplayPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gameplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameAIBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gamePlayerBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        gameplayPane.setLayer(gamePlayerBoard, javax.swing.JLayeredPane.DEFAULT_LAYER);
        gameplayPane.setLayer(gameAIBoard, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(rulesPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gameplayPane))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(rulesPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gameplayPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BattleshipFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BattleshipFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BattleshipFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BattleshipFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BattleshipFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel battleshipLogo;
    private javax.swing.JLayeredPane gameAIBoard;
    private javax.swing.JLayeredPane gamePlayerBoard;
    private javax.swing.JLayeredPane gameplayPane;
    private javax.swing.JButton highscoresButton;
    private javax.swing.JTextField nameEntry;
    private javax.swing.JButton rulesButton;
    private javax.swing.JButton rulesClose;
    private javax.swing.JLabel rulesLabel;
    private javax.swing.JLayeredPane rulesPane;
    private javax.swing.JLabel rulesText;
    private javax.swing.JButton startButton;
    private javax.swing.JLayeredPane startPane;
    // End of variables declaration//GEN-END:variables
}
